apiVersion: v1
kind: Service
metadata:
  name: test-python-server-service
spec:
  type: NodePort
  selector:
    app: test-python-server # Label selector matching your deployment
  ports:
    - protocol: TCP
      port: 80 # Port on which the service will be accessible
      targetPort: 8080 # Port on the pods to which traffic will be forwarded
      nodePort: 30001 # Port on the nodes to which traffic will be forwarded
